### PR TITLE
Allow extra parameters to be passed on to XPtr objective function

### PR DESCRIPTION
**Pull request by jolars**
This pull request adds the option of passing additional arguments through ... and via Rcpp::DE::EvalCompiled to compiled objective functions. This was inspired by the Rmalschains package, from which some of the code was adopted. I am not completely confident that list2env(list(...)) is the best way to handle this but it seems more streamlined than using a separate environment argument (as Rmalschains does).

I also adjusted one of the tests to invoke and test this functionality and had to add a typedef, funcPtrTest, to make the tests work as before.

If I'm not mistaken, this shouldn't mean any user-visible differences.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
Looks clean at first glance without coffee.

I thought we had an example somewhere here that did that via the `env`.  Also, `genrose` example generalization is good. I may initially have had them just for comparison.

**Comment by jolars** [comment]
Perhaps you mean `demo("environment", "RcppDE")`? It don't think it works anymore since the `env` argument was dropped. I get `Error in (function (x)  : unused argument (env = <environment>)`

**Comment by eddelbuettel** [comment]
Could well be; it has been awhile.

If you are (at least semi-actively) using RcppDE, any interest in tackling mutlithreaded mode?  I ran myself into a corner a few years when I tried to 'one' of several streans of a RNG to be identical to its stream in serial mode.  And I just don't think you can.  So "identical" results may be off the table, but "about the same by a given \epsilon" and faster may be good enough.  Interested?

**Review by eddelbuettel — APPROVED** [review]

**Comment by jolars** [comment]
Yeah, sure, I might be interested in that. I suppose [this](https://github.com/rforge/rcpp/tree/master/pkg/RcppParDE) is the attempt that you are referring to? Do you have any preference in regards to Intel TBB (RcppParallel) vs OpenMP?

**Comment by eddelbuettel** [comment]
The narrower option would be to revive OpenMP, and "just" work our a parallel RNG.

But you are quite right that RcppParallel could fit the pill as well.  Not sure.

**Pull request merged**
